#ifndef HERMES_PEBBLE_PROTOCOL_H
#define HERMES_PEBBLE_PROTOCOL_H

#include <stdint.h>

#define HERMES_WATCH_UUID "7d07aa22-7d13-48c1-a400-2602a5ae4647"
#define HERMES_PROTOCOL_VERSION 1u
#define HERMES_APP_MESSAGE_INBOX_SIZE 1024u
#define HERMES_APP_MESSAGE_OUTBOX_SIZE 1024u
#define HERMES_MAX_CHUNKS 6u
#define HERMES_CHUNK_PAYLOAD_SIZE 192u
#define HERMES_MAX_TRANSFER_BYTES 1024u
#define HERMES_MAX_DICTATION_BYTES 1024u
#define HERMES_MAX_RECENT_ITEMS 3u
#define HERMES_MAX_RESULT_PAGE_BYTES 768u
#define HERMES_CHUNK_TIMEOUT_SECONDS 15u
#define HERMES_DURABLE_RECEIPT_TIMEOUT_SECONDS 30u
#define HERMES_RETRY_DELAY_1_SECONDS 1u
#define HERMES_RETRY_DELAY_2_SECONDS 2u
#define HERMES_RETRY_DELAY_4_SECONDS 4u
#define HERMES_RETRY_DELAY_8_SECONDS 8u
#define HERMES_MAX_RETRY_COUNT 4u
#define HERMES_STORAGE_CHUNK_SIZE 192u
#define HERMES_STORAGE_META_SIZE 48u
#define HERMES_STORAGE_MAX_VALUE 240u

#define HERMES_KEY_PROTOCOL_VERSION 0u
#define HERMES_KEY_MESSAGE_KIND 1u
#define HERMES_KEY_TRANSFER_ID 2u
#define HERMES_KEY_CAPTURE_ID 3u
#define HERMES_KEY_CHUNK_INDEX 4u
#define HERMES_KEY_CHUNK_COUNT 5u
#define HERMES_KEY_PAYLOAD 6u
#define HERMES_KEY_STATUS 7u
#define HERMES_KEY_ERROR_CODE 8u
#define HERMES_KEY_ITEM_ID 9u
#define HERMES_KEY_ITEM_STATE 10u
#define HERMES_KEY_ITEM_KIND 11u
#define HERMES_KEY_PAGE_OFFSET 12u
#define HERMES_KEY_PAGE_COUNT 13u
#define HERMES_KEY_TOTAL_BYTES 14u
#define HERMES_KEY_CONVERSATION_GENERATION 15u
#define HERMES_KEY_FLAGS 16u
#define HERMES_KEY_CORRELATION_ID 17u

#define HERMES_FLAG_MORE 0x01u
#define HERMES_FLAG_STOP_REQUESTED 0x02u
#define HERMES_FLAG_REPLAYED 0x04u
#define HERMES_FLAG_DURABLE_COMMIT 0x08u

#define HERMES_KIND_NONE 0u
#define HERMES_KIND_HANDSHAKE 1u
#define HERMES_KIND_SUBMIT_REQUEST 2u
#define HERMES_KIND_SAVE_NOTE 3u
#define HERMES_KIND_DISCARD_CAPTURE 4u
#define HERMES_KIND_FETCH_RECENT 5u
#define HERMES_KIND_FETCH_RESULT 6u
#define HERMES_KIND_START_CONVERSATION 7u
#define HERMES_KIND_STOP_REQUEST 8u
#define HERMES_KIND_INK_BLOCK 9u
#define HERMES_KIND_AUDIO_STATUS 10u
#define HERMES_KIND_HANDSHAKE_ACK 101u
#define HERMES_KIND_DURABLE_RECEIPT 102u
#define HERMES_KIND_STATUS_UPDATE 103u
#define HERMES_KIND_RECENT_PAGE 104u
#define HERMES_KIND_RESULT_PAGE 105u
#define HERMES_KIND_NEW_CONVERSATION_ACK 106u
#define HERMES_KIND_STRUCTURED_ERROR 107u
#define HERMES_KIND_CAPTURE_DISCARDED 108u
#define HERMES_KIND_INK_RECEIPT 109u
#define HERMES_KIND_AUDIO_BEGIN 110u
#define HERMES_KIND_AUDIO_BLOCK 111u
#define HERMES_KIND_AUDIO_PLAY 112u
#define HERMES_KIND_AUDIO_CANCEL 113u

// Audio v1: at most two seconds of 8 kHz mono signed 8-bit PCM.
#define HERMES_AUDIO_MAX_BYTES 16000u
#define HERMES_AUDIO_FORMAT 1u
#define HERMES_AUDIO_READY 1u
#define HERMES_AUDIO_BUFFERED 2u
#define HERMES_AUDIO_COMPLETE 3u
#define HERMES_AUDIO_MUTED 4u
#define HERMES_AUDIO_BUSY 5u
#define HERMES_AUDIO_INVALID 6u
#define HERMES_AUDIO_FAILED 7u
#define HERMES_AUDIO_CANCELLED 8u
#define HERMES_AUDIO_QUIET_TIME 9u

#define HERMES_STATUS_NONE 0u
#define HERMES_STATUS_WAITING_PHONE 1u
#define HERMES_STATUS_SAVED_QUEUED 2u
#define HERMES_STATUS_SUBMITTING 3u
#define HERMES_STATUS_ACCEPTED 4u
#define HERMES_STATUS_WORKING 5u
#define HERMES_STATUS_APPROVAL_NEEDED 6u
#define HERMES_STATUS_COMPLETED 7u
#define HERMES_STATUS_FAILED 8u
#define HERMES_STATUS_STOPPING 9u
#define HERMES_STATUS_CANCELLED 10u
#define HERMES_STATUS_INTERRUPTED 11u
#define HERMES_STATUS_OUTCOME_UNKNOWN 12u
#define HERMES_STATUS_NOTE_SAVED 13u
#define HERMES_STATUS_WAITING_PROFILE 14u
#define HERMES_STATUS_DISCARDED 15u

#define HERMES_ERROR_NONE 0u
#define HERMES_ERROR_PROTOCOL_VERSION 1u
#define HERMES_ERROR_UNSUPPORTED_KIND 2u
#define HERMES_ERROR_MALFORMED 3u
#define HERMES_ERROR_TRANSFER_BOUND 4u
#define HERMES_ERROR_DUPLICATE_CHUNK 5u
#define HERMES_ERROR_DURABLE_STORAGE 6u
#define HERMES_ERROR_CONNECTION_SETTINGS 7u
#define HERMES_ERROR_AUTHENTICATION 8u
#define HERMES_ERROR_NETWORK_TLS 9u
#define HERMES_ERROR_REDIRECT 10u
#define HERMES_ERROR_UNSUPPORTED_ROUTE 11u
#define HERMES_ERROR_INVALID_RESPONSE 12u
#define HERMES_ERROR_UNKNOWN_OUTCOME 13u
#define HERMES_ERROR_NOT_FOUND 14u
#define HERMES_ERROR_IDEMPOTENCY_CONFLICT 15u
#define HERMES_ERROR_SERVER 16u
#define HERMES_ERROR_NOTE_STORAGE 17u
#define HERMES_ERROR_WATCH_UNAVAILABLE 18u

#define HERMES_ITEM_KIND_NONE 0u
#define HERMES_ITEM_KIND_REQUEST 1u
#define HERMES_ITEM_KIND_NOTE 2u

#define HERMES_PENDING_NONE 0u
#define HERMES_PENDING_REQUEST 1u
#define HERMES_PENDING_NOTE 2u

#define HERMES_STORAGE_KEY_INSTALL 1u
#define HERMES_STORAGE_KEY_COUNTER 2u
#define HERMES_STORAGE_KEY_GENERATION 3u
#define HERMES_STORAGE_KEY_PENDING_META 4u
#define HERMES_STORAGE_KEY_TOUCH_NAVIGATION 5u
#define HERMES_STORAGE_KEY_CHUNK_BASE 8u

#define HERMES_PENDING_MAGIC 0x32505448u
#define HERMES_PENDING_FORMAT_VERSION 1u
#define HERMES_PENDING_COMMIT 0xa5u

#endif
